linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gci
    #- gochecknoglobals
    #- gochecknoinits
    #- gocognit
    #- goconst
    #- gocritic
    - gocyclo
    #- godot
    - godox
    #- goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - golint
    #- gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    #- nakedret
    #- nestif
    #- nlreturn
    #- noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    #- unparam
    - unused
    - varcheck
    - whitespace
    #- wsl

run:
  skip-dirs:
    - pkg/components/helper/client_helper
    - pkg/components/id/client_id
  skip-files:
    - ".*__generated\\.go$"

linters-settings:
  dupl:
    threshold: 300
  funlen:
    lines: 200
    statements: 100
  lll:
    line-length: 240
    tab-width: 1

issues:
  exclude-rules:
    - linters:
        - golint
      text: "don't use ALL_CAPS in Go names; use CamelCase"
      path: pkg/consts/enums
    - linters:
        - gosec
      text: "G101: Potential hardcoded credentials"
    - linters:
        - staticcheck
      text: "SA1019: package github.com/golang/protobuf/proto is deprecated"
    - linters:
        - stylecheck
      text: "ST1003: should not use ALL_CAPS in Go names; use CamelCase instead"
      path: pkg/consts/enums
